In [1]:
import pandas as pd

In [2]:
df_op = pd.read_csv(r'4000 series operating data.csv')

/var/folders/kv/prbqh_rs7mb2996w25cq7rth0000gn/T/ipykernel_1423/1546557224.py:1: DtypeWarning: Columns (2,3,4,5,6,7,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_op = pd.read_csv(r'4000 series operating data.csv')

In [3]:
df_op

,Date and time,Batch,LIQUID,LIQUID.1,LIQUID.2,LIQUID.3,LIQUID.4,LIQUID.5,pH,GAS,GAS.1,GAS.2,GAS.3,OFFGAS,OFFGAS.1,PRESSURE,PRESSURE.1,OXYGEN
0,NaN,NaN,INFLOW,INFLOW,INFLOW,INFLOW,INFLOW,INFLOW,NaN,INFLOW,INFLOW,INFLOW,INFLOW,1.00,2.00,1.00,2.00,NaN
1,NaN,NaN,1,2,3,4,5,6,NaN,1,2,3,4,NaN,NaN,NaN,NaN,NaN
2,04/02/2019 08:46,4030.0,1049.57,25.91,14.44,NaN,297.73,14980.00,5.76,NaN,NaN,NaN,55.14,1.87,16.94,1.79,5.15,6.78
3,04/02/2019 09:01,4030.0,1049.09,25.62,13.54,NaN,357.44,15000.00,5.79,NaN,NaN,NaN,56.88,1.89,20.52,1.80,5.16,8.39
4,04/02/2019 09:16,4030.0,1049.61,25.44,13.59,NaN,356.83,15010.00,5.80,NaN,NaN,NaN,56.03,1.94,23.77,1.80,5.15,8.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83201,25/05/2021 21:15,4053.0,889.62,0.02,0.01,0.0,0.14,12910.0,5.83,11668.37,33.2,39.5,0.0,0.72,4.46,2.00,5.11,113.78
83202,25/05/2021 21:20,4053.0,888.61,0.02,0.01,0.0,0.07,20210.0,5.72,11283.46,29.42,34.63,0.0,0.68,4.43,1.99,5.09,114.99
83203,25/05/2021 21:25,4053.0,890.29,0.02,0.01,0.0,0.09,20950.0,5.62,10838.39,26.67,30.97,0.0,0.65,4.49,1.99,5.07,115.00
83204,25/05/2021 21:30,4053.0,878.23,0.02,0.01,0.0,0.14,20960.0,5.53,10510.03,24.3,27.7,0.0,0.63,4.48,2.00,5.04,115.00
83205,25/05/2021 21:35,4053.0,872.84,0.02,0.01,0.0,0.09,21000.0,5.45,9864.2,22.59,25.46,0.0,0.62,4.39,1.99,5.00,115.00

In [4]:
# Basis on above output, re-naming columns and removing the first 2 rows
df_op.rename(columns={'LIQUID': 'LIQUID INFLOW 1', 'LIQUID.1': 'LIQUID INFLOW 2', 'LIQUID.2': 'LIQUID INFLOW 3',
                      'LIQUID.3': 'LIQUID INFLOW 4', 'LIQUID.4': 'LIQUID INFLOW 5', 'LIQUID.5': 'LIQUID INFLOW 6',
                      'GAS': 'GAS INFLOW 1', 'GAS.1': 'GAS INFLOW 2', 'GAS.2': 'GAS INFLOW 3', 'GAS.3': 'GAS INFLOW 4',
                      'OFFGAS': 'OFFGAS 1', 'OFFGAS.1': 'OFFGAS 2', 'PRESSURE': 'PRESSURE 1','PRESSURE.1': 'PRESSURE 2'},
            inplace=True)

In [5]:
df_op = df_op.iloc[2:].reset_index(drop=True)

In [6]:
df_op['Batch'].isna().sum()

np.int64(0)

In [7]:
# Since no NaN as confirmed above, converting Batch to type integer
df_op['Batch'] = df_op['Batch'].astype(int)

In [8]:
df_op['Batch'].unique()

array([4030, 4032, 4033, 4034, 4035, 4036, 4037, 4038, 4039, 4040, 4041,
       4042, 4043, 4044, 4045, 4046, 4047, 4048, 4050, 4051, 4052, 4053])

In [9]:
df_p = pd.read_excel(r'4000 series product data.xlsx')

In [10]:
df_p.rename(columns={'Product': 'Product (g/litre)'}, inplace=True)

In [11]:
df_p = df_p.iloc[2:].reset_index(drop=True)

In [12]:
df_p.dtypes

Date and time         object
Batch                float64
Product (g/litre)     object
dtype: object

In [13]:
df_p['Batch'].isna().sum()

np.int64(0)

In [14]:
# Since no NaN
df_p['Batch'] = df_p['Batch'].astype(int)

In [15]:
len(df_p['Batch'].unique())

21

In [16]:
df_p['Product (g/litre)'].isna().sum()

np.int64(19)

In [17]:
df_p[df_p['Product (g/litre)'].isna()]

            Date and time  Batch Product (g/litre)
7     2019-02-04 15:00:00   4030               NaN
283   2019-04-16 12:00:00   4032               NaN
1141  2019-11-10 12:00:00   4037               NaN
1687  2020-03-21 20:00:00   4041               NaN
1688  2020-03-22 00:00:00   4041               NaN
1689  2020-03-22 04:00:00   4041               NaN
1690  2020-03-22 08:00:00   4041               NaN
1691  2020-03-22 12:00:00   4041               NaN
1692  2020-03-22 15:00:00   4041               NaN
1693  2020-03-22 20:00:00   4041               NaN
1694  2020-03-23 00:00:00   4041               NaN
1695  2020-03-23 04:00:00   4041               NaN
1696  2020-03-23 08:00:00   4041               NaN
1697  2020-03-23 12:00:00   4041               NaN
1698  2020-03-23 15:00:00   4041               NaN
1699  2020-03-23 20:00:00   4041               NaN
1700  2020-03-24 00:00:00   4041               NaN
1716  2020-03-26 15:00:00   4041               NaN
3005  2021-03-05 23:30:00   4052               NaN

In [18]:
df_p.groupby('Batch')['Product (g/litre)'].mean()

Batch
4030    24.511466
4032    24.623969
4033    24.800353
4034    25.052205
4035    24.647115
4036    24.449189
4037    23.710458
4038      23.8392
4039    23.869182
4040    26.450455
4041     27.26327
4042    26.367835
4043    27.041068
4044    25.463488
4045    26.591552
4046    26.017734
4047    26.370833
4048     23.77087
4050    21.477518
4051    22.792512
4052    25.787324
Name: Product (g/litre), dtype: object

In [19]:
liquid_cols = [col for col in df_op.columns if 'LIQUID INFLOW' in col]

df_op[liquid_cols] = df_op[liquid_cols].apply(pd.to_numeric, errors='coerce')

In [20]:
liquid_cols

['LIQUID INFLOW 1',
 'LIQUID INFLOW 2',
 'LIQUID INFLOW 3',
 'LIQUID INFLOW 4',
 'LIQUID INFLOW 5',
 'LIQUID INFLOW 6']

In [21]:
df_op['TOTAL LIQUID INFLOW'] = df_op[liquid_cols].sum(axis=1)

In [22]:
df_product_rate_per_batch = df_op.groupby('Batch')['TOTAL LIQUID INFLOW'].mean() * df_p.groupby('Batch')['Product (g/litre)'].mean() * 0.001

In [23]:
df_product_rate_per_batch

Batch
4030    616.305179
4032    621.162886
4033    608.869223
4034    622.196071
4035    606.416985
4036    609.172327
4037    568.419365
4038    593.373544
4039    581.763278
4040     651.30302
4041    670.229408
4042    645.844169
4043    669.367477
4044    621.672935
4045    640.864621
4046    644.787017
4047    663.082829
4048    596.268039
4050    536.552036
4051    549.661318
4052    629.353928
4053           NaN
dtype: object

In [24]:
df_product_rate_per_batch.sort_values(ascending=False)

Batch
4041    670.229408
4043    669.367477
4047    663.082829
4040     651.30302
4042    645.844169
4046    644.787017
4045    640.864621
4052    629.353928
4034    622.196071
4044    621.672935
4032    621.162886
4030    616.305179
4036    609.172327
4033    608.869223
4035    606.416985
4048    596.268039
4038    593.373544
4039    581.763278
4037    568.419365
4051    549.661318
4050    536.552036
4053           NaN
dtype: object